### ISSUE TITLE
ncurses support

### ISSUE THREAD

**Issue by HenryYoung42** [pasis/xmppconsole#3]
I'm building an XMPP server and this would be a great debugging tool. But I need to run it in a command line only environment with no desktop and no gtk. How close/far are you with this ? Can I help ?

**Comment by pasis** [comment]
Ncurses UI should work. It doesn't support multi-line input, so you will need to type complex stanzas in a single line.

Now, xmppconsole is a simple tool. It does its job, but can be more powerful and more convenient. You can simply try it out and see what you would like to add.

Let me know if you need help with building it.

**Comment by pasis** [comment]
I have just checked ncurses module and realized that it doesn't support scrolling and terminal window resizing. Without scrolling support you need a large terminal window not to miss output.

**Comment by HenryYoung42** [comment]
When I run ./configure it reports:

checking for gtk... no
configure: error: gtk+-3.0 is required

I plan to run it from command line with no desktop (it's a headless server). I would prefer not to install gtk because of the huge number of dependent packages. Is there something I can do to work around the need for gtk ?

Is it as easy as removing the PKG_CHECK_MODULES for gtk in configure.ac. Perhaps it is also required by the linker even if not used at runtime ?

**Comment by pasis** [comment]
Yeah, I need to improve autotools scripts, so one can build only modules they want. I'll add `--disable-gtk`, etc. Meanwhile you can remove gtk checks in configure.ac, but also you will need to remove gtk based code. The easiest way is to comment code in `ui_gtk.c` and comment block related to gtk module in `ui.c`

**Comment by pasis** [comment]
I've updated autotools scripts, so now you can build only required UI modules. By default, it builds only those modules which have all required dependencies. You can control what to build with `--disable-gtk` and `--disable-ncurses`.

**Comment by HenryYoung42** [comment]
That is great - than you so much. I will give this a try and report back !

**Comment by HenryYoung42** [comment]
I just tested this and it works perfectly. I'm developing an xmpp server gateway to another messaging system, with the gateway normally running per user on 127.0.0.1 / localhost. So xmppconsole is the perfect test client for debugging the client/server interactions. Thanks for fixing it so I can build without needing gtk installed.

**Comment by HenryYoung42** [comment]
Closing issue because the build system has been improved with the ability to build without needing gtk installed.

**Comment by pasis** [comment]
Ncurses UI has been improved. Now, it supports terminal window resizing and scrolling (Ctrl+Up/Down, mouse wheel in some terminals)

**Comment by HenryYoung42** [comment]
Great news. :)
